# Generated by Django 4.1.5 on 2023-01-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('two wheeler', 'two wheeler'), ('three wheeler', 'three wheeler'), ('four wheeler', 'four wheeler')], default='two wheeler', max_length=20)),
                ('vehicle_model', models.CharField(max_length=20)),
                ('vehicle_description', models.CharField(max_length=50)),
            ],
        ),
    ]
