# Generated by Django 4.1.5 on 2023-01-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(choices=[('two wheeler', 'two wheeler'), ('three wheeler', 'three wheeler'), ('four wheeler', 'four wheeler')], default='two wheeler', max_length=30)),
                ('vehicle_model', models.CharField(max_length=20)),
                ('vehicle_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='vehicle',
        ),
    ]
