# Generated by Django 4.1.5 on 2023-01-27 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0002_vehicle_detail_delete_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_detail',
            name='vehicle_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
